# Reference only — the real users_database.yml is generated by ../setup.sh
# (never commit the generated file; it holds your password hash).
users:
  your-username:
    disabled: false
    displayname: 'Your Name'
    password: '$argon2id$...generated-by-setup.sh...'
    email: you@example.com
    groups: []
